
package app.fx.soap.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ConsultaRucPort", targetNamespace = "http://wsoap.com/pwserver/consulta")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaRucPort {


    /**
     * 
     * @param consultaRucRequest
     * @return
     *     returns app.fx.soap.wsdl.ConsultaRucResponse
     */
    @WebMethod
    @WebResult(name = "consultaRucResponse", targetNamespace = "http://wsoap.com/pwserver/consulta", partName = "consultaRucResponse")
    public ConsultaRucResponse consultaRuc(
        @WebParam(name = "consultaRucRequest", targetNamespace = "http://wsoap.com/pwserver/consulta", partName = "consultaRucRequest")
        ConsultaRucRequest consultaRucRequest);

}
