
package app.fx.soap.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsultaRucPortService", targetNamespace = "http://wsoap.com/pwserver/consulta", wsdlLocation = "http://localhost:8097/ws/consultaRuc.wsdl")
public class ConsultaRucPortService
    extends Service
{

    private final static URL CONSULTARUCPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTARUCPORTSERVICE_EXCEPTION;
    private final static QName CONSULTARUCPORTSERVICE_QNAME = new QName("http://wsoap.com/pwserver/consulta", "ConsultaRucPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8097/ws/consultaRuc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARUCPORTSERVICE_WSDL_LOCATION = url;
        CONSULTARUCPORTSERVICE_EXCEPTION = e;
    }

    public ConsultaRucPortService() {
        super(__getWsdlLocation(), CONSULTARUCPORTSERVICE_QNAME);
    }

    public ConsultaRucPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARUCPORTSERVICE_QNAME, features);
    }

    public ConsultaRucPortService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARUCPORTSERVICE_QNAME);
    }

    public ConsultaRucPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARUCPORTSERVICE_QNAME, features);
    }

    public ConsultaRucPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaRucPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaRucPort
     */
    @WebEndpoint(name = "ConsultaRucPortSoap11")
    public ConsultaRucPort getConsultaRucPortSoap11() {
        return super.getPort(new QName("http://wsoap.com/pwserver/consulta", "ConsultaRucPortSoap11"), ConsultaRucPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaRucPort
     */
    @WebEndpoint(name = "ConsultaRucPortSoap11")
    public ConsultaRucPort getConsultaRucPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsoap.com/pwserver/consulta", "ConsultaRucPortSoap11"), ConsultaRucPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARUCPORTSERVICE_EXCEPTION!= null) {
            throw CONSULTARUCPORTSERVICE_EXCEPTION;
        }
        return CONSULTARUCPORTSERVICE_WSDL_LOCATION;
    }

}
